allowBuilds:
  core-js: true
  esbuild: true
  lightningcss: true
  rolldown: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - lightningcss
  - rolldown
